site_name: Tech Writer Days
theme:
    name: material
    logo: TWD_logo.png
    favicon: TWD_favicon.png
    features:
        - navigation.tabs
    font: false # отключает скачивание шрифтов для отрисовки темы материал из Гугла
extra_css:
    - material-styles.css
nav:
    - Как запустить первый портал?:
        - Вот так: my-first-portal.md
    - Дом: index.md
markdown_extensions:
    - pymdownx.superfences # более гибкое оформление блоков https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
    - admonition
plugins:
    - search:
        lang:
          - ru